---
- name: where does it get that file to ? 
  become: yes
  hosts: all
  tasks: 
    - name: copy a file from sowhere
      copy: 
        src: /myfiles/foo.txt
        dest: /foo.txt
    - name: fetch a file from sowhere
      fetch: 
        src: /bar.txt
        dest: /myfiles/bar.txt
