---
- name: Let's make a Tartiflette
  hosts: localhost
  connection: local
  gather_facts: no

  vars: 
    ingredients:
      vegetables:
        onions: 2
        potatoes: 5
      cheese: "raclette"

  tasks:

    - name: Adding Vegetables
      debug: 
        msg: "Adding {{ item.value }} {{ item.key }}"
      with_dict: "{{ ingredients.vegetables }}"
        
    - name: Adding Cheese
      debug: 
        msg: "Adding {{ ingredients.cheese }}"
        
    - name: Make Tartiflette 
      debug: 
        var:  ingredients
        
    - name: Splunk FW
      uri:
        url: "{{ splunk_hec }}"
        method: POST
        validate_certs: no
        body_format: json
        body: 
            event:
              modern_kitchen: "{{ ingredients }}"
        headers: 
          Authorization: "Splunk {{ splunk_token }}"
